version: '3.9'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    shm_size: '4gb'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
        - mariadb
    ports:
      - 8080:8080

volumes:
  mariadb:
    driver: local
  adminer:
    driver: local