export const RequestsPath = {
  PAYMENT_INFO: '/payment/info',
  PAYMENT: '/payment',
  SHOPPING_CART: '/shopping-cart',
  SHOPPING_CART_COUNT: '/shopping-cart/count',
  SHOPPING_CART_ALL: '/shopping-cart/all',
  SHOPPING_CART_TOTAL_PRICE: '/shopping-cart/total-price',
  REMOVE_ITEM_FROM_CART: '/shopping-cart/one/',
  ADD_TO_CART: '/shopping-cart/add',
  LOGOUT: '/users/logout',
  LOGIN: '/users/login',
  REGISTER: '/users/signup',
  BOILER_PARTS: '/boiler-parts',
  BOILER_PARTS_NEW: '/boiler-parts/new',
  BOILER_PARTS_BESTSELLERS: '/boiler-parts/bestsellers',
  BOILER_PARTS_FIND: '/boiler-parts/find',
  LOGIN_CHECK: '/users/login-check',
};
